name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          check-latest: true
      - run: npm i
      - run: npm run test:actions
